import{a as v,s as m,i as f}from"./assets/vendor-DTsp5xqr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))s(i);new MutationObserver(i=>{for(const r of i)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(i){const r={};return i.integrity&&(r.integrity=i.integrity),i.referrerPolicy&&(r.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?r.credentials="include":i.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(i){if(i.ep)return;i.ep=!0;const r=n(i);fetch(i.href,r)}})();const M="https://pixabay.com/api/";async function p(t,e=1,n){try{return(await v.get(M,{params:{key:"45476779 - a37d3eb685934422065bcfa30",image_type:"photo",orientation:"horizontal",safesearch:!0,q:t,page:e,per_page:15}})).data}catch(s){console.error("Fetch error: ",s)}}const g=document.querySelector(".gallery");function w({webformatURL:t,largeImageURL:e,tags:n,likes:s,views:i,comments:r,downloads:a}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${e}"><img class="list-img" src="${t}" alt="${n}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${s}</p></li>
      <li class="figcaption-item">Views<p class="counter">${i}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${r}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${a}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function h(t){return t.map(w).join("")}function E(t){const e=h(t);g.innerHTML=e}function q(t){const e=h(t);g.insertAdjacentHTML("beforeend",e)}const o={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector('[name="text"]'),ul:document.querySelector("ul"),btnLoadMore:document.querySelector(".load-more")};let y=0,c,l=1;o.formEl.addEventListener("submit",async t=>{try{if(t.preventDefault(),L(),c=o.input.value.trim(),l=1,!c)S();else{const e=await p(c,l);y=Math.ceil(e.totalHits/15),e.hits.length===0&&x(),E(e.hits),b(75);const n=new m(".gallery a");e.hits.length<15?(o.btnLoadMore.classList.add("visually-hidden"),u()):o.btnLoadMore.classList.remove("visually-hidden"),o.formEl.addEventListener("click",s=>{s.target.name==="text"&&(o.input.value="")})}}catch(e){console.log(e.message)}d()});o.btnLoadMore.addEventListener("click",async()=>{if(o.btnLoadMore.classList.add("visually-hidden"),L(),l===y)return o.btnLoadMore.classList.add("visually-hidden"),d(),u();l+=1;const t=await p(c,l);q(t.hits),new m(".gallery a").refresh(),d(),b(),o.btnLoadMore.classList.remove("visually-hidden"),t.hits.length<15&&(o.btnLoadMore.classList.add("visually-hidden"),u())});function S(){return console.log("sdsd"),o.ul.innerHTML="",o.btnLoadMore.classList.add("visually-hidden"),f.error({message:"Please fill in the input field",position:"topRight"})}function x(){f.error({message:"Image is not found",position:"topRight"})}function u(){f.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"})}function L(){o.btnLoadMore.insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>')}function d(){document.querySelector(".loader").remove()}function b(t){const e=o.ul.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t||e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
